services:
  api:
    build: ./fastapi-backend
    env_file: .env
    container_name: voltuj-api
    ports:
      - "3000:80" # Ujisti se, že 8000 už není obsazené něčím jiným
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - voltuj-network

  ocpp:
    build: ./ocpp-backend
    env_file: .env
    container_name: voltuj-ocpp
    ports:
      - "9001:9000"
    depends_on:
      - redis
      - api
    restart: unless-stopped
    networks:
      - voltuj-network

  db:
    image: postgres:16
    container_name: voltuj-db
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - voltuj-network

  redis:
    image: redis:7
    container_name: voltuj-redis
    restart: unless-stopped
    networks:
      - voltuj-network

volumes:
  pgdata:

networks:
  voltuj-network:
    driver: bridge